apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jira-proxy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: address-lb-jira-proxy
    networking.gke.io/managed-certificates: jira-proxy
    kubernetes.io/ingress.class: "gce"
spec: 
  backend: 
    serviceName: jira-proxy
    servicePort: 80
