apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jira-proxy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-jira-proxy
    networking.gke.io/managed-certificates: jira-proxy
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec: 
  rules:
  - http: 
     paths: 
     - path: /healthy
       backend: 
        serviceName: jira-proxy
        servicePort: 80
