apiVersion: v1
kind: Service
metadata:
  name: jira-proxy
  labels:
    app: jira-proxy
    service: jira-proxy
  annotations:
    cloud.google.com/backend-config: '{"default": "jira-proxy-backendconfig"}'
spec:
  selector:
    app: jira-proxy
  ports:
    - name: http
      port: 80
      targetPort: APP_PORT
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jira-proxy
  labels:
    account: jira-proxy
