apiVersion: v1
kind: Service
metadata:
  annotations: 
    cloud.google.com/backend-config: '{"default": "jira-backendconfig"}'
  name: jira-proxy
  labels:
    app: jira-proxy
    service: jira-proxy
spec:
  selector:
    app: jira-proxy
  ports:
    - name: http
      port: 80
      targetPort: APP_PORT
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jira-proxy
  labels:
    account: jira-proxy
